version: '3'
services:
  dev-db:
    image: postgres:14
    container_name: postgres_db
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes: 
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    driver: local